# CodeBuild buildspec file for killing/reviving the MWAA env via Terraform

version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - cd /tmp
      - echo "Installing Terraform"
      - curl -o terraform_${TERRAFORM_VERSION}_linux_amd64.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - unzip -o terraform_${TERRAFORM_VERSION}_linux_amd64.zip && mv terraform /usr/bin
      - terraform --version
  build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}
      - bash -c "${TF_INIT_COMMAND}"
      - bash -c "${TF_APPLY_COMMAND}"
  post_build:
    commands:
      - echo Kill Switch Performed completed on `date`